In [2]:
# Célula 1 - Imports e configurações iniciais

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from datetime import datetime
import unicodedata

# Configurações de exibição do pandas
pd.set_option("display.max_columns", 120)
pd.set_option("display.width", 160)

print("Bibliotecas importadas com sucesso!")
print(f"Pandas versão: {pd.__version__}")

Bibliotecas importadas com sucesso!
Pandas versão: 3.0.5

In [3]:
# Célula 2 - Criar estrutura de pastas via Python

RAIZ = Path("..")  # Volta uma pasta pois estamos dentro de notebooks/

PASTAS = [
    "dados_brutos",
    "dados_tratados",
    "notebooks",
    "sql",
    "dashboards",
    "relatorios",
    "apresentacao",
    "logs"
]

for pasta in PASTAS:
    (RAIZ / pasta).mkdir(parents=True, exist_ok=True)

print("Pastas verificadas/criadas:")
for pasta in PASTAS:
    print("--", RAIZ / pasta)

Pastas verificadas/criadas:
-- ..\dados_brutos
-- ..\dados_tratados
-- ..\notebooks
-- ..\sql
-- ..\dashboards
-- ..\relatorios
-- ..\apresentacao
-- ..\logs

In [5]:
# Célula 3 - Parâmetros do projeto (ATUALIZADO)

RAIZ = Path("..")

ARQUIVO_BRUTO = RAIZ / "dados_brutos" / "dados_abertos_prf-datatran2025.csv"
ARQUIVO_BASE_ANALITICA = RAIZ / "dados_tratados" / "base_analitica_prf_2025.csv"
ARQUIVO_BASE_MODELAVEL = RAIZ / "dados_tratados" / "base_modelavel_prf_2025.csv"
ARQUIVO_DICIONARIO = RAIZ / "dados_tratados" / "dicionario_variaveis_modulo4.csv"
ARQUIVO_DECISOES = RAIZ / "logs" / "decisoes_tratamento_modulo4.md"
ARQUIVO_README = RAIZ / "README.md"

SEPARADOR = ";"
ENCODING_ENTRADA = "latin1"
ENCODING_SAIDA = "utf-8-sig"

print("Parâmetros definidos:")
print(f"Arquivo bruto: {ARQUIVO_BRUTO}")
print(f"Base analítica: {ARQUIVO_BASE_ANALITICA}")
print(f"Base modelável: {ARQUIVO_BASE_MODELAVEL}")

Parâmetros definidos:
Arquivo bruto: ..\dados_brutos\dados_abertos_prf-datatran2025.csv
Base analítica: ..\dados_tratados\base_analitica_prf_2025.csv
Base modelável: ..\dados_tratados\base_modelavel_prf_2025.csv

In [6]:
# Célula 4 - Verificar se o arquivo existe

print(f"Verificando arquivo: {ARQUIVO_BRUTO}")
print(f"Arquivo existe? {ARQUIVO_BRUTO.exists()}")

if ARQUIVO_BRUTO.exists():
    print("✅ Arquivo encontrado com sucesso!")
else:
    print("❌ Arquivo NÃO encontrado. Verifique:")
    print(f"   - O nome do arquivo está correto?")
    print(f"   - O arquivo está dentro da pasta 'dados_brutos'?")
    print("   - Arquivos disponíveis em dados_brutos/:")
    for arquivo in (RAIZ / "dados_brutos").iterdir():
        print(f"       - {arquivo.name}")

Verificando arquivo: ..\dados_brutos\dados_abertos_prf-datatran2025.csv
Arquivo existe? True
✅ Arquivo encontrado com sucesso!

In [7]:
# Célula 5 - Função para ler CSV com múltiplos encodings

def ler_csv_prf(caminho, sep=";", encodings=("latin1", "utf-8", "utf-8-sig")):
    """
    Tenta ler o CSV com diferentes encodings até encontrar um que funcione.
    """
    ultimo_erro = None
    for enc in encodings:
        try:
            print(f"Tentando leitura com encoding={enc}...")
            df = pd.read_csv(caminho, sep=sep, encoding=enc, low_memory=False)
            print(f"✅ Leitura bem-sucedida com encoding={enc}")
            return df
        except Exception as erro:
            ultimo_erro = erro
            print(f"❌ Falhou com {enc}: {erro}")
    
    print(f"❌ Todos os encodings falharam.")
    raise ultimo_erro

# Executar a leitura
df = ler_csv_prf(ARQUIVO_BRUTO, sep=SEPARADOR)

# Visualizar as primeiras linhas
print("\n📊 Primeiras linhas do DataFrame:")
display(df.head())

Tentando leitura com encoding=latin1...
✅ Leitura bem-sucedida com encoding=latin1

📊 Primeiras linhas do DataFrame:

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,classificacao_acidente,fase_dia,sentido_via,condicao_metereologica,tipo_pista,tracado_via,uso_solo,pessoas,mortos,feridos_leves,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
0,652493,2025-01-01,quarta-feira,06:20:00,SP,116,225,GUARULHOS,Reação tardia ou ineficiente do condutor,Tombamento,Com Vítimas Feridas,Pleno dia,Decrescente,Céu Claro,Múltipla,Reta;Declive,Sim,2,0,1,0,0,1,1,2,"-23,48586772","-46,54075317",SPRF-SP,DEL01-SP,UOP01-DEL01-SP
1,652519,2025-01-01,quarta-feira,07:50:00,CE,116,"546,2",PENAFORTE,Pista esburacada,Colisão frontal,NaN,Pleno dia,Crescente,Céu Claro,Simples,Reta,Não,6,1,1,0,1,4,1,6,"-7,812288","-39,08333306",SPRF-CE,DEL05-CE,UOP03-DEL05-CE
2,652522,2025-01-01,quarta-feira,08:45:00,PR,369,"88,2",CORNELIO PROCOPIO,Reação tardia ou ineficiente do condutor,Colisão traseira,Com Vítimas Feridas,Pleno dia,Crescente,Sol,Dupla,Reta;Aclive,Sim,5,0,3,0,2,0,3,2,"-23,182565","-50,637228",SPRF-PR,DEL07-PR,UOP05-DEL07-PR
3,652544,2025-01-01,quarta-feira,11:00:00,PR,116,74,CAMPINA GRANDE DO SUL,Reação tardia ou ineficiente do condutor,Saída de leito carroçável,Com Vítimas Feridas,Pleno dia,Crescente,Céu Claro,Dupla,Reta,Não,5,0,1,0,4,0,1,2,"-25,36517687","-49,04223028",SPRF-PR,DEL01-PR,UOP02-DEL01-PR
4,652549,2025-01-01,quarta-feira,09:30:00,MG,251,471,FRANCISCO SA,Velocidade Incompatível,Colisão frontal,Com Vítimas Feridas,Pleno dia,Decrescente,Chuva,Simples,Curva;Declive,Não,5,0,1,1,1,2,2,4,"-16,46801304","-43,43121303",SPRF-MG,DEL12-MG,UOP01-DEL12-MG

In [8]:
# Célula 6 - Padronizar nomes das colunas

import unicodedata

def normalizar_nome_coluna(nome):
    """
    Padroniza nomes de colunas:
    - Minúsculas
    - Sem acentos
    - Espaços e caracteres especiais substituídos por underline
    """
    nome = str(nome).strip().lower()
    # Remove acentos
    nome = unicodedata.normalize("NFKD", nome).encode("ascii", "ignore").decode("utf-8")
    # Substitui espaços e caracteres especiais por underline
    nome = nome.replace(" ", "_").replace("-", "_").replace("/", "_")
    # Remove underlines duplicados
    while "__" in nome:
        nome = nome.replace("__", "_")
    return nome.strip("_")

# Aplicar padronização
df.columns = [normalizar_nome_coluna(c) for c in df.columns]

# Compatibilização de grafias possíveis
renomear = {
    "condicao_meteorologica": "condicao_metereologica"
}
df = df.rename(columns={k: v for k, v in renomear.items() if k in df.columns})

print("✅ Nomes das colunas padronizados!")
print(f"Total de colunas: {len(df.columns)}")
print("\n📋 Lista de colunas:")
print(df.columns.tolist())

✅ Nomes das colunas padronizados!
Total de colunas: 30

📋 Lista de colunas:
['id', 'data_inversa', 'dia_semana', 'horario', 'uf', 'br', 'km', 'municipio', 'causa_acidente', 'tipo_acidente', 'classificacao_acidente', 'fase_dia', 'sentido_via', 'condicao_metereologica', 'tipo_pista', 'tracado_via', 'uso_solo', 'pessoas', 'mortos', 'feridos_leves', 'feridos_graves', 'ilesos', 'ignorados', 'feridos', 'veiculos', 'latitude', 'longitude', 'regional', 'delegacia', 'uop']

In [9]:
# Célula 7 - Conferir colunas esperadas

colunas_esperadas = [
    "data_inversa", "dia_semana", "horario", "uf", "br", "municipio",
    "causa_acidente", "tipo_acidente", "classificacao_acidente",
    "fase_dia", "condicao_metereologica", "tipo_pista", "tracado_via",
    "uso_solo", "pessoas", "mortos", "feridos_leves",
    "feridos_graves", "feridos", "veiculos"
]

# Verificar quais colunas esperadas estão presentes
colunas_presentes = [c for c in colunas_esperadas if c in df.columns]
colunas_faltantes = [c for c in colunas_esperadas if c not in df.columns]

print(f"✅ Colunas esperadas presentes: {len(colunas_presentes)}/{len(colunas_esperadas)}")

if colunas_faltantes:
    print(f"\n⚠️ Colunas faltantes ({len(colunas_faltantes)}):")
    for col in colunas_faltantes:
        print(f"   - {col}")
    print("\n💡 Dica: Verifique se o dicionário oficial da PRF mudou.")
else:
    print("\n✅ Todas as colunas esperadas estão presentes!")

✅ Colunas esperadas presentes: 20/20

✅ Todas as colunas esperadas estão presentes!

In [10]:
# Célula 8 - Retrato inicial da base

print("📊 RETRATO INICIAL DA BASE")
print("=" * 60)

print(f"📏 Dimensões: {df.shape[0]} linhas x {df.shape[1]} colunas")

print("\n📋 Primeiras 5 linhas:")
display(df.head())

print("\n🎲 Amostra aleatória de 5 linhas:")
display(df.sample(5, random_state=42))

print("\n📝 Informações gerais do DataFrame:")
df.info()

📊 RETRATO INICIAL DA BASE
============================================================
📏 Dimensões: 72529 linhas x 30 colunas

📋 Primeiras 5 linhas:

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,classificacao_acidente,fase_dia,sentido_via,condicao_metereologica,tipo_pista,tracado_via,uso_solo,pessoas,mortos,feridos_leves,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
0,652493,2025-01-01,quarta-feira,06:20:00,SP,116,225,GUARULHOS,Reação tardia ou ineficiente do condutor,Tombamento,Com Vítimas Feridas,Pleno dia,Decrescente,Céu Claro,Múltipla,Reta;Declive,Sim,2,0,1,0,0,1,1,2,"-23,48586772","-46,54075317",SPRF-SP,DEL01-SP,UOP01-DEL01-SP
1,652519,2025-01-01,quarta-feira,07:50:00,CE,116,"546,2",PENAFORTE,Pista esburacada,Colisão frontal,NaN,Pleno dia,Crescente,Céu Claro,Simples,Reta,Não,6,1,1,0,1,4,1,6,"-7,812288","-39,08333306",SPRF-CE,DEL05-CE,UOP03-DEL05-CE
2,652522,2025-01-01,quarta-feira,08:45:00,PR,369,"88,2",CORNELIO PROCOPIO,Reação tardia ou ineficiente do condutor,Colisão traseira,Com Vítimas Feridas,Pleno dia,Crescente,Sol,Dupla,Reta;Aclive,Sim,5,0,3,0,2,0,3,2,"-23,182565","-50,637228",SPRF-PR,DEL07-PR,UOP05-DEL07-PR
3,652544,2025-01-01,quarta-feira,11:00:00,PR,116,74,CAMPINA GRANDE DO SUL,Reação tardia ou ineficiente do condutor,Saída de leito carroçável,Com Vítimas Feridas,Pleno dia,Crescente,Céu Claro,Dupla,Reta,Não,5,0,1,0,4,0,1,2,"-25,36517687","-49,04223028",SPRF-PR,DEL01-PR,UOP02-DEL01-PR
4,652549,2025-01-01,quarta-feira,09:30:00,MG,251,471,FRANCISCO SA,Velocidade Incompatível,Colisão frontal,Com Vítimas Feridas,Pleno dia,Decrescente,Chuva,Simples,Curva;Declive,Não,5,0,1,1,1,2,2,4,"-16,46801304","-43,43121303",SPRF-MG,DEL12-MG,UOP01-DEL12-MG

🎲 Amostra aleatória de 5 linhas:

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,classificacao_acidente,fase_dia,sentido_via,condicao_metereologica,tipo_pista,tracado_via,uso_solo,pessoas,mortos,feridos_leves,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
6366,691804,2025-03-15,sábado,12:30:00,ES,101,67,SAO MATEUS,Condutor desrespeitou a iluminação vermelha do...,Colisão transversal,Com Vítimas Feridas,Pleno dia,Crescente,Sol,Simples,Rotatória,Sim,4,0,0,2,1,2,2,4,"-18,72802869","-39,85997558",SPRF-ES,DEL04-ES,UOP02-DEL04-ES
9405,704622,2025-07-13,domingo,22:30:00,PE,423,"74,1",JUPI,Condutor deixou de manter distância do veículo...,Colisão traseira,Sem Vítimas,Plena Noite,Decrescente,Céu Claro,Simples,Aclive;Reta,Sim,2,0,0,0,2,0,0,2,"-8,7160879","-36,4219923",SPRF-PE,DEL03-PE,UOP01-DEL03-PE
26102,663260,2025-02-23,domingo,18:10:00,BA,242,231,ITABERABA,Animais na Pista,Atropelamento de Animal,Com Vítimas Feridas,Plena Noite,Decrescente,Céu Claro,Simples,Reta,Sim,1,0,1,0,0,0,1,1,"-12,511706","-40,324247",SPRF-BA,DEL06-BA,UOP02-DEL06-BA
28616,667036,2025-03-13,quinta-feira,19:55:00,DF,20,"9,9",BRASILIA,Reação tardia ou ineficiente do condutor,Engavetamento,Com Vítimas Feridas,Plena Noite,Crescente,Céu Claro,Dupla,Reta,Não,6,0,4,0,2,0,4,3,"-15,6502715","-47,7763723",SPRF-DF,DEL02-DF,UOP01-DEL02-DF
1696,660353,2025-02-09,domingo,19:05:00,MA,222,665,ACAILANDIA,Pedestre andava na pista,Atropelamento de Pedestre,Com Vítimas Feridas,Plena Noite,Decrescente,Céu Claro,Simples,Declive,Não,3,0,1,1,0,1,2,3,"-4,89367779","-47,38426513",SPRF-MA,DEL04-MA,UOP03-DEL04-MA

📝 Informações gerais do DataFrame:
<class 'pandas.DataFrame'>
RangeIndex: 72529 entries, 0 to 72528
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      72529 non-null  int64
 1   data_inversa            72529 non-null  str
 2   dia_semana              72529 non-null  str
 3   horario                 72529 non-null  str
 4   uf                      72529 non-null  str
 5   br                      72529 non-null  int64
 6   km                      72529 non-null  str
 7   municipio               72529 non-null  str
 8   causa_acidente          72529 non-null  str
 9   tipo_acidente           72529 non-null  str
 10  classificacao_acidente  72528 non-null  str
 11  fase_dia                72529 non-null  str
 12  sentido_via             72529 non-null  str
 13  condicao_metereologica  72529 non-null  str
 14  tipo_pista              72529 non-null  str
 15  tracado_via             72529 non-null  str
 16  uso_solo                72529 non-null  str
 17  pessoas                 72529 non-null  int64
 18  mortos                  72529 non-null  int64
 19  feridos_leves           72529 non-null  int64
 20  feridos_graves          72529 non-null  int64
 21  ilesos                  72529 non-null  int64
 22  ignorados               72529 non-null  int64
 23  feridos                 72529 non-null  int64
 24  veiculos                72529 non-null  int64
 25  latitude                72529 non-null  str
 26  longitude               72529 non-null  str
 27  regional                72527 non-null  str
 28  delegacia               72507 non-null  str
 29  uop                     72491 non-null  str
dtypes: int64(10), str(20)
memory usage: 16.6 MB

In [11]:
# Célula 9 - Tipos de dados e memória

print("📊 DIAGNÓSTICO DE TIPOS DE DADOS")
print("=" * 60)

print("\n📋 Informações do DataFrame:")
df.info(memory_usage="deep")

print("\n📊 Resumo dos tipos de dados:")
resumo_tipos = (
    df.dtypes.astype(str)
    .value_counts()
    .rename_axis("tipo")
    .reset_index(name="qtd_colunas")
)
display(resumo_tipos)

print("\n💡 Observações:")
print("- Colunas do tipo 'object' geralmente são textos/categorias")
print("- Colunas 'int64' são números inteiros")
print("- Colunas 'float64' são números decimais")
print("- Datas ainda podem estar como 'object' (precisam ser convertidas)")

📊 DIAGNÓSTICO DE TIPOS DE DADOS
============================================================

📋 Informações do DataFrame:
<class 'pandas.DataFrame'>
RangeIndex: 72529 entries, 0 to 72528
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      72529 non-null  int64
 1   data_inversa            72529 non-null  str
 2   dia_semana              72529 non-null  str
 3   horario                 72529 non-null  str
 4   uf                      72529 non-null  str
 5   br                      72529 non-null  int64
 6   km                      72529 non-null  str
 7   municipio               72529 non-null  str
 8   causa_acidente          72529 non-null  str
 9   tipo_acidente           72529 non-null  str
 10  classificacao_acidente  72528 non-null  str
 11  fase_dia                72529 non-null  str
 12  sentido_via             72529 non-null  str
 13  condicao_metereologica  72529 non-null  str
 14  tipo_pista              72529 non-null  str
 15  tracado_via             72529 non-null  str
 16  uso_solo                72529 non-null  str
 17  pessoas                 72529 non-null  int64
 18  mortos                  72529 non-null  int64
 19  feridos_leves           72529 non-null  int64
 20  feridos_graves          72529 non-null  int64
 21  ilesos                  72529 non-null  int64
 22  ignorados               72529 non-null  int64
 23  feridos                 72529 non-null  int64
 24  veiculos                72529 non-null  int64
 25  latitude                72529 non-null  str
 26  longitude               72529 non-null  str
 27  regional                72527 non-null  str
 28  delegacia               72507 non-null  str
 29  uop                     72491 non-null  str
dtypes: int64(10), str(20)
memory usage: 92.7 MB

📊 Resumo dos tipos de dados:

    tipo  qtd_colunas
0    str           20
1  int64           10

💡 Observações:
- Colunas do tipo 'object' geralmente são textos/categorias
- Colunas 'int64' são números inteiros
- Colunas 'float64' são números decimais
- Datas ainda podem estar como 'object' (precisam ser convertidas)

In [12]:
# Célula 10 - Diagnóstico de valores ausentes

print("📊 DIAGNÓSTICO DE VALORES AUSENTES")
print("=" * 60)

# Calcular nulos por coluna
nulos = pd.DataFrame({
    "qtd_nulos": df.isnull().sum(),
    "perc_nulos": (df.isnull().sum() / len(df)) * 100
}).sort_values("perc_nulos", ascending=False)

# Filtrar apenas colunas com nulos
nulos_com_nulos = nulos[nulos["qtd_nulos"] > 0]

if len(nulos_com_nulos) > 0:
    print(f"✅ Encontradas {len(nulos_com_nulos)} colunas com valores ausentes:")
    display(nulos_com_nulos)
    
    print("\n📌 Colunas com maior percentual de nulos:")
    display(nulos_com_nulos.head(10))
else:
    print("✅ Nenhum valor ausente encontrado!")

print(f"\n📊 Total de células: {df.shape[0] * df.shape[1]}")
print(f"📊 Total de nulos: {df.isnull().sum().sum()}")
print(f"📊 Percentual de nulos no total: {(df.isnull().sum().sum() / (df.shape[0] * df.shape[1])) * 100:.2f}%")

📊 DIAGNÓSTICO DE VALORES AUSENTES
============================================================
✅ Encontradas 4 colunas com valores ausentes:

                        qtd_nulos  perc_nulos
uop                            38    0.052393
delegacia                      22    0.030333
regional                        2    0.002758
classificacao_acidente          1    0.001379

📌 Colunas com maior percentual de nulos:

                        qtd_nulos  perc_nulos
uop                            38    0.052393
delegacia                      22    0.030333
regional                        2    0.002758
classificacao_acidente          1    0.001379

📊 Total de células: 2175870
📊 Total de nulos: 63
📊 Percentual de nulos no total: 0.00%

In [13]:
# Célula 11 - Diagnóstico de duplicidades

print("📊 DIAGNÓSTICO DE DUPLICIDADES")
print("=" * 60)

qtd_duplicadas = df.duplicated().sum()
print(f"🔍 Linhas duplicadas exatas: {qtd_duplicadas}")

if qtd_duplicadas > 0:
    print(f"📊 Percentual de duplicatas: {(qtd_duplicadas / len(df)) * 100:.2f}%")
    
    # Remover duplicatas
    df = df.drop_duplicates().copy()
    print(f"✅ Duplicatas removidas. Nova dimensão: {df.shape}")
else:
    print("✅ Nenhuma duplicata encontrada!")

📊 DIAGNÓSTICO DE DUPLICIDADES
============================================================
🔍 Linhas duplicadas exatas: 0
✅ Nenhuma duplicata encontrada!

In [14]:
# Célula 12 - Cardinalidade das categorias

print("📊 CARDINALIDADE DAS VARIÁVEIS CATEGÓRICAS")
print("=" * 60)

# Selecionar apenas colunas do tipo object (categóricas)
categoricas = df.select_dtypes(include="object").columns

if len(categoricas) > 0:
    # Calcular quantidade de categorias por variável
    cardinalidade = (
        df[categoricas]
        .nunique(dropna=True)
        .sort_values(ascending=False)
        .reset_index()
    )
    cardinalidade.columns = ["variavel", "qtd_categorias"]
    
    print(f"✅ {len(categoricas)} variáveis categóricas encontradas:")
    display(cardinalidade)
    
    print("\n📌 Variáveis com alta cardinalidade (muitas categorias):")
    display(cardinalidade.head(10))
    
    # Destacar variáveis com muitas categorias
    print("\n💡 Observações:")
    print("- 'municipio' tende a ter muitas categorias (centenas de municípios)")
    print("- 'causa_acidente' e 'tipo_acidente' precisam de atenção")
    print("- Categorias raras podem distorcer análises")
else:
    print("⚠️ Nenhuma variável categórica encontrada!")

📊 CARDINALIDADE DAS VARIÁVEIS CATEGÓRICAS
============================================================
✅ 20 variáveis categóricas encontradas:

C:\Users\claud\AppData\Local\Temp\ipykernel_11292\1650039504.py:7: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categoricas = df.select_dtypes(include="object").columns

                  variavel  qtd_categorias
0                 latitude           69294
1                longitude           69237
2                       km            7655
3                municipio            1844
4                  horario            1412
5              tracado_via             605
6                      uop             395
7             data_inversa             365
8                delegacia             153
9           causa_acidente              69
10                regional              28
11                      uf              27
12           tipo_acidente              17
13  condicao_metereologica               9
14              dia_semana               7
15                fase_dia               4
16             sentido_via               3
17  classificacao_acidente               3
18              tipo_pista               3
19                uso_solo               2

📌 Variáveis com alta cardinalidade (muitas categorias):

         variavel  qtd_categorias
0        latitude           69294
1       longitude           69237
2              km            7655
3       municipio            1844
4         horario            1412
5     tracado_via             605
6             uop             395
7    data_inversa             365
8       delegacia             153
9  causa_acidente              69

💡 Observações:
- 'municipio' tende a ter muitas categorias (centenas de municípios)
- 'causa_acidente' e 'tipo_acidente' precisam de atenção
- Categorias raras podem distorcer análises